In [17]:

import numpy as np

# ===== 第一阶段：基础操作 =====
print("=== 1. 数组创建 ===")
# 示例
arr1_example = np.arange(10)
print("示例输出:", arr1_example)

# 任务模板
def task1():
    """创建从5到15的浮点数数组（步长0.5）"""
    # 你的代码写在这里
    result = np.arange(5,15,0.5)
    return result

print(task1())

print("\n=== 2. 形状变换 ===")
# 示例
arr2_example = np.array([1,2,3,4,5,6]).reshape(2,3)
print("示例输出:\n", arr2_example)

# 任务模板
def task2():
    """将0-11的数组转为3x4矩阵"""
    arr = np.arange(12)
    # 你的代码写在这里
    result = arr.reshape(3,4)
    return result

print(task2())

print("\n=== 3. 索引切片 ===")
# 示例
arr3_example = np.random.rand(5,5)
print("示例输出:", arr3_example[:,1])  # 第2列

# 任务模板
def task3():
    """从5x5矩阵中提取中心3x3区域"""
    matrix = np.random.rand(5,5)
    # 你的代码写在这里
    result = matrix[1:4,1:4]
    return result

print(task3())

# ===== 第二阶段：向量化运算 =====
print("\n=== 4. 基本运算 ===")
# 示例
arr4_example = np.array([1,2,3])
print("示例输出:", arr4_example ** 2)

# 任务模板
def task4():
    """计算数组各元素的自然对数"""
    arr = np.array([1,2,np.e])
    # 你的代码写在这里
    result = np.log(arr)
    return result

print(task4())

# ===== 第二阶段：向量化运算 =====
print("\n=== 5. 条件过滤 ===")
# 示例
arr5_example = np.array([3, 6, 2, 8, 1, 0.3, -0.7])
print("示例输出:", arr5_example[arr5_example > 5])  # 输出[6 8]

# 任务模板
def task5():
    """找出数组中绝对值小于0.5的元素"""
    arr = np.random.randn(10)  # 生成10个标准正态分布随机数
    # 你的代码写在这里
    result = arr[np.abs(arr) < 0.5]
    return result

print(task5())

print("\n=== 6. 广播机制 ===")
# 示例
matrix6_example = np.array([[1,2,3],[4,5,6]])
vector6_example = np.array([1,0,-1])
print("示例输出:\n", matrix6_example + vector6_example)

# 任务模板
def task6():
    """实现矩阵每列乘不同的系数"""
    matrix = np.random.rand(3,4)  # 3行4列矩阵
    coeffs = np.array([0.5, 1.0, 1.5, 2.0])  # 4个系数
    # 你的代码写在这里
    result = matrix * coeffs  # 广播机制自动应用
    return result

print(task6())

# ===== 第三阶段：数学函数 =====
print("\n=== 7. 统计计算 ===")
# 示例
arr7_example = np.random.rand(3,4)
print("示例输出(列平均):", np.mean(arr7_example, axis=0))

# 任务模板
def task7():
    """计算3D数组每个通道的标准差"""
    arr_3d = np.random.rand(5,5,3)  # 5x5图像，3个通道
    # 你的代码写在这里
    result = np.std(arr_3d,axis = (0,1))
    return result

print(task7())

print("\n=== 8. 线性代数 ===")
# 示例
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("示例输出(矩阵乘法):\n", A @ B)

# 任务模板
def task8():
    """实现向量投影计算"""
    v = np.array([3,4])  # 被投影向量
    u = np.array([1,0])  # 投影方向
    # 你的代码写在这里
    proj = np.dot(v,u)/np.dot(u,u) * u
    return proj

print(task8())

# ===== 第四阶段：高级应用 =====
print("\n=== 9. 图像处理 ===")
# 示例
def rgb2gray_example(rgb):
    return np.dot(rgb[...,:3], [0.299, 0.587, 0.114])

# 任务模板
def task9():
    """实现图像亮度调整（乘系数+截断）"""
    img = np.random.rand(256,256,3)*255
    # 你的代码写在这里
    return result

def task9(brightness_factor=1.2):
    img = np.random.rand(256,256,3)*255
    adjusted = img * brightness_factor  # 亮度调整
    result = np.clip(adjusted, 0, 255).astype(np.uint8)  # 截断+类型转换
    return result



print("\n=== 10. 信号处理 ===")
# 示例
def moving_avg_example(signal):
    return np.convolve(signal, np.ones(3)/3, 'valid')

# 任务模板
def task10():
    """实现一阶差分边缘检测"""
    signal = np.random.randn(100)
    # 你的代码写在这里
    return result

def task10():
    signal = np.random.randn(100)
    edges = np.diff(signal)  # 一阶差分
    # 也可以这样实现：
    # edges = np.convolve(signal, [1, -1], 'valid')
    return edges


if __name__ == "__main__":
    print("所有任务模板已定义，直接调用taskX()函数完成练习")


=== 1. 数组创建 ===
示例输出: [0 1 2 3 4 5 6 7 8 9]
[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5
 12.  12.5 13.  13.5 14.  14.5]

=== 2. 形状变换 ===
示例输出:
 [[1 2 3]
 [4 5 6]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

=== 3. 索引切片 ===
示例输出: [0.45322791 0.66610695 0.40654996 0.39651087 0.02922188]
[[0.38143739 0.70159296 0.41897614]
 [0.96676281 0.72546182 0.33868083]
 [0.64358598 0.19778826 0.3435065 ]]

=== 4. 基本运算 ===
示例输出: [1 4 9]
[0.         0.69314718 1.        ]

=== 5. 条件过滤 ===
示例输出: [6. 8.]
[ 0.24819299 -0.06318212 -0.32997119]

=== 6. 广播机制 ===
示例输出:
 [[2 2 2]
 [5 5 5]]
[[0.15703715 0.11958148 1.17252628 0.70031535]
 [0.45887296 0.5778167  0.47271704 0.73867458]
 [0.10096391 0.08542234 0.65802266 1.02038891]]

=== 7. 统计计算 ===
示例输出(列平均): [0.55702659 0.45386183 0.3380172  0.38177432]
[0.26689477 0.26952927 0.27609299]

=== 8. 线性代数 ===
示例输出(矩阵乘法):
 [[19 22]
 [43 50]]
[3. 0.]

=== 9. 图像处理 ===

=== 10. 信号处理 ===
所有任务模板已定义，直接调用taskX()函数完成练习
