# nmupy！

我们在第一节课说过，python取消了数据类型的设计，现在你即使存一个1，也是一个对象了（相对的，传统的语言要求指明每个数据的类型，我们将之称其为静态数据类型的语言）。

我们打开python的源代码，注意python的实现是c语言实现的，你创建一个变量，python会把它自动的关联到一个结构体上，这个结构体就包含了它的浮点形和整形，布尔型，字符串等等，当你在不同的地方调用这个变量时，python又会自动的找到你试图操作的变量此时应该调用的数据类型。

但是你显然不难想到，这是不是有点太浪费时间和空间了，事实上确实是这样的，原生python的效率实在难以言说（加之它还是一个解释性语言），假设我们需要一个处理大量数据的代码，而全部的这些数据都是同样的类型，那岂不是浪费了及其大量的空间，特别的，我有的时候不需要如此高的精度，譬如全部的数据范围不超4位的shortint，那我干嘛用32位double存它呢？因此我们这里开始就要引入numpy了，这是一个用于高效加载，存储和处理内存的库，这个库作为数据科学的基础，在后面的代码中会经常出现

In [2]:
#使用这个代码引入numpy
import numpy as np
#绝大多数的人喜欢把这个库别名为np

## 作为一个例子，python的固定类型数组，以及从头开始创建的numpy数组

python给了一个库叫array，他提供的一个类可以支持操作固定类型的数组，这作为一个例子，用来比较numpy的数组

In [4]:
import array
import numpy as np
from timeit import timeit
# 测试数组大小
size = 1000000
# 1. Python原生array测试
def test_python_array():
    # 创建数组
    py_arr = array.array('d', [i*0.1 for i in range(size)])
    # 计算求和
    total = sum(py_arr)
    return total
# 2. NumPy数组测试
def test_numpy_array():
    # 创建数组
    np_arr = np.arange(0, size*0.1, 0.1)
    # 计算求和
    total = np.sum(np_arr)
    return total
# 运行时间测试
py_time = timeit(test_python_array, number=10)
np_time = timeit(test_numpy_array, number=10)
# 结果输出
print("=== 求和操作性能对比 ===")
print(f"Python原生array求和: {py_time/10:.6f} 秒/次 (10次平均)")
print(f"NumPy数组求和: {np_time/10:.6f} 秒/次 (10次平均)")

=== 求和操作性能对比 ===
Python原生array求和: 0.110356 秒/次 (10次平均)
NumPy数组求和: 0.003055 秒/次 (10次平均)


## numpy的数组

使用numpy.array([python原生列表])创建一个np数组

numpy要求数组（这里我们改称更合适的名字，数组）必须为同一类型的数据，如果你试图写出一个不匹配的数据，那它会认为这里面的数都是最高等级的数，以保证数据存在,如果你希望强制指定这个数组里的类型，你可以array类构造器中的dtype=，并且数组的类型不会因为你传入一个数而改变整个的类型，一个例子是，如果你尝试把一个浮点数置入整形的数组，那么它会直接截断这个数，就好像浮点数转换成整数一样

In [5]:
#numpy会尝试向上转换（如果可行），譬如这里的整数会被转换为浮点数
arr1 = np.array([3.14,2,5])
print(arr1)
#对照的，全是整数的
arr2 = np.array([3,2,5])
print(arr2)

[3.14 2.   5.  ]
[3 2 5]


In [6]:
arr1 = np.array([3,2,5],dtype='float32')
print(arr1)
#这里给出的全部是整数，但是强制指定了它的类型，于是吐出来的就全部是浮点数

[3. 2. 5.]


此外，numpy传入的列表内部嵌套的列表被认为是数组的第二个维度，提前说一嘴，这里的访问方式也更贴近数学而非代码

In [7]:
arr1 = np.array([[2,3,4],
                [4,5,6],
                [7,8,9]]
               )
print(arr1)

[[2 3 4]
 [4 5 6]
 [7 8 9]]


### 下面一个内容是，nmupy提供的一次性创建数组方法

面对大型数组时，用它内部提供的方法创建一个数组是一个更好的办法,下面的例子展示了这类方法,还挺多的

In [8]:
#创建一个长度为10的全零数组
arr1 = np.zeros(10,dtype=int)
print(arr1)
print()
#创建一个3*5的浮点数数组,数组的值都为1
arr2 = np.ones((3,5),dtype = float)
print(arr2)
print()
#创建一个3*5的数组,并填满3.14
arr3 = np.full((3,5),3.14)
print(arr3)
print()
#创建一个线性序列数组,从0开始,从20结束,步长为2
arr4 = np.arange(0,20,2)
print(arr4)
print()
#创建一个元素的值在0~1中均匀分布的数组,长5个元素
arr5 = np.linspace(0,1,5)
print(arr5)
print()
#创建一个元素随机分布在0~1中的数组,大小为3*3
arr6 = np.random.random((3,3))
print(arr6)
print()
#创建一个元素服从均值为0,标准差为1的正态分布~N(0,1)的数组,大小为3*3
arr7 = np.random.normal(0,1,(3,3))
print(arr7)
print()
#创建一个元素是[0,10)间的随机整数的数组,大小为3*3
arr8 = np.random.randint(0,10,(3,3))
print(arr8)
#创建一个3*3的单位矩阵
arr9 = np.eye(3)
print(arr9)
print()
#创建一个长为3的空数组,注意到,空数组的初始值是其内存空间内的上一个值,认为是随机的
arr10 = np.empty(3)
print(arr10)
print()

[0 0 0 0 0 0 0 0 0 0]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]

[ 0  2  4  6  8 10 12 14 16 18]

[0.   0.25 0.5  0.75 1.  ]

[[0.33575712 0.96468848 0.32282892]
 [0.70441282 0.44589435 0.56607963]
 [0.79831006 0.25099642 0.98599308]]

[[ 0.49070557  0.28892807 -0.63901731]
 [-0.03045178 -0.40796099  0.27250339]
 [-1.59029599 -0.3208204  -1.17690595]]

[[3 4 2]
 [6 7 8]
 [1 6 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[1. 1. 1.]



### numpy的标准数据类型

它给你提供了基础的数据类型,有如下几个,你可以向上面演示的那样用‘int16’来写，也可以用np中自带的numpy常量对象来指定np.int16

| &zwnj;**类型分类**&zwnj;       | &zwnj;**数据类型**&zwnj;   | &zwnj;**描述**&zwnj;                          | &zwnj;**取值范围**&zwnj;                     | &zwnj;**内存占用**&zwnj; |
|--------------------|---------------|-----------------------------------|----------------------------------|--------------|
| &zwnj;**布尔型**&zwnj;         | `bool_`       | 存储 True/False                   | True 或 False                    | 1 字节       |
| &zwnj;**有符号整型**&zwnj;     | `int8`        | 8 位整数                          | -128 到 127                     | 1 字节       |
|                    | `int16`       | 16 位整数                         | -32768 到 32767                 | 2 字节       |
|                    | `int32`       | 32 位整数（默认）                 | -2³¹ 到 2³¹-1                  | 4 字节       |
|                    | `int64`       | 64 位整数                         | -2⁶³ 到 2⁶³-1                  | 8 字节       |
| &zwnj;**无符号整型**&zwnj;     | `uint8`       | 8 位无符号整数                    | 0 到 255                        | 1 字节       |
|                    | `uint16`      | 16 位无符号整数                   | 0 到 65535                      | 2 字节       |
|                    | `uint32`      | 32 位无符号整数                   | 0 到 4294967295                 | 4 字节       |
|                    | `uint64`      | 64 位无符号整数                   | 0 到 2⁶⁴-1                     | 8 字节       |
| &zwnj;**浮点型**&zwnj;         | `float16`     | 半精度浮点数                     | ±65504 范围，3 位有效数字       | 2 字节       |
|                    | `float32`     | 单精度浮点数                     | ±1.18e⁻³⁸~3.4e³⁸，6-7 位有效数字 | 4 字节       |
|                    | `float64`     | 双精度浮点数（默认）             | ±2.23e⁻³⁰⁸~1.79e³⁰⁸，15-16 位   | 8 字节       |
| &zwnj;**复数型**&zwnj;         | `complex64`   | 32 位复数（两个 float32）        | 实部/虚部同 float32             | 8 字节       |
|                    | `complex128`  | 64 位复数（两个 float64）        | 实部/虚部同 float64             | 16 字节      |
| &zwnj;**特殊类型**&zwnj;       | `intc`        | C 兼容的 int 类型                | 平台相关                        | 通常 4 字节  |
|                    | `intp`        | 索引类型（类似 size_t）          | 平台相关                        | 通常 8 字节  |


### numpy的数组，他有什么属性？

一个numpy数组含有的属性有：大小，形状，存储大小，数据类型
下面几个例子介绍了这个玩意儿

In [9]:
#首先得到几个演示数组
np.random.seed(0)  #这个指定随机种子，种子一定，下面随机出来的数就是随机取出但每次相同的
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))
print(x1)
print(x2)
print(x3)
print("------")
#ndim获得数组的维度
print(x1.ndim,x2.ndim,x3.ndim)
#shape是数组的大小
print(x1.shape,x2.shape,x3.shape)
#size是数组的总元素数量
print(x1.size,x2.size,x3.size)
#dtype是数据类型
print(x1.dtype,x2.dtype,x3.dtype)
#每个数组元素的大小用itemsize
print(x1.itemsize,x2.itemsize,x3.itemsize)
#数组的总大小是nbytes，这里的计算是每个元素大小itemsize*元素数量size就等于总大小nbytes
print(x1.nbytes,x2.nbytes,x3.nbytes)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
------
1 2 3
(6,) (3, 4) (3, 4, 5)
6 12 60
int32 int32 int32
4 4 4
24 48 240


你也可以用 数组名[索引] 的方式,来获取数组的某一个元素,同样的,首个从0开始,逆序索引用负的索引值,你也可以通过索引值指定的修改数组中的某个元素,多维数组中通过多元列表的索引值获得数据,而非 数组名[第一维][第二维] 

In [10]:
#仍随机获得两个示例
np.random.seed(0) 
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
print(x1)
print(x2)
print()
#用索引获得他的值
print(x1[1])
#多维数组的索引更接近于向量
print(x2[1,1])
#用索引修改值
x1[1] = 2
print(x1[1])
#逆序索引是负的,但是0只有一个,是数组头,也就是说-0 = +0 = 0,并且从后向前数的第一位是-1
print(x1[-1])
print(x1[-0])

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

0
6
2
9
5


我们前面说过,类型不对的修改在numpy中会引起问题,譬如我将一个浮点数插入到整形数组里,会直接截断掉小数部分

In [11]:
x1 = np.array([5,0,3,3,7,9],dtype=np.int8)
print(x1)
x1[1] = 3.1415926
print(x1)

[5 0 3 3 7 9]
[5 3 3 3 7 9]


### 数组的切分，变形，拼接，分裂

切片很好用,这里也能用,使用 数组名[起点索引:终点索引:步长]来切原数组的一部分下来,但是和python列表的切片不同的是,这里的切片仍在原来的数组上,并没有给你一个新的数组

此外,若不指定起始/终止位置,他会默认从头开始/数组的维度大小(也就是切到底),不指定步长默认步长为1

In [12]:
x1 = np.array([5,0,3,3,7,9])
#切分一个片段
x2 = x1[1:4]
print(x1,x2)
#切下来的部分还在原来的数组上
x2[1] = 10
print(x1,x2)
#按步长切
x3 = x1[::2]
print(x3)
#不指定起点
x4 = x1[:2]
print(x4)
#不指定终点
x5 = x1[1:]
print(x5)

[5 0 3 3 7 9] [0 3 3]
[ 5  0 10  3  7  9] [ 0 10  3]
[ 5 10  7]
[5 0]
[ 0 10  3  7  9]


同样的,你也可以[::-1]获得逆序

In [13]:
x1 = np.array([5,0,3,3,7,9])
#切分一个片段
x2 = x1[::-1]
print(x1,x2)

[5 0 3 3 7 9] [9 7 3 3 0 5]


多维数组的切片是在每一个维度中按照上述规则切,譬如

x1 = [[5 0 3 3]

 [7 9 3 5]
 
 [2 4 7 6]]

我们将其视作x1=[x2,x3,x4],其中的x2=[5 0 3 3],x3=[7 9 3 5],x4=[2 4 7 6]

这时,你希望从x1中切出后半部分,你可以这样写x5 = x1[1:],此时你会得到的数组是[x2,x3],然后你又想要在x2和x3中切出后半部分,你还需要x2[2:],这时表达规则要按照上面多元索引的规则,写成x6 = x1[1:,2:]

简言之,对于一个矩阵而言,首个位置的切片切的是首个维度,第二个切的是第二个维度,以此类推

In [14]:
#仍随机获得两个示例
np.random.seed(0) 
x2 = np.random.randint(10,size=(3,4))
#行从第二行开始往后,列从第二列开始往后
x3 = x2[1:,2:]
print(x2,'\n\n',x3)
#行取首两行,列取首三列
x4 = x2[:2,:3]
print('\n',x4)
#前两行中隔一个取一列
x5 = x2[:2,::2]
print('\n',x5)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

 [[3 5]
 [7 6]]

 [[5 0 3]
 [7 9 3]]

 [[5 3]
 [7 3]]


此外,[前面没有:后面也没有]同样表示切满,所以这种方式可以快速的得到逆序

In [15]:
#仍随机获得两个示例
np.random.seed(0) 
x2 = np.random.randint(10,size=(3,4))

x3 = x2[::-1,::-1]
print(x2,'\n\n',x3)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

 [[6 7 4 2]
 [5 3 9 7]
 [3 3 0 5]]


一种常见的需求是得到一行或者是一列,这个可以通过索引值和切片的混合使用来解决,特别要说的是,上面的模型还指出了,如果想要获得一个子数组,那么直接在外数组的索引时单取一个数组下标也可以,这样得到的是一个行

In [16]:
#仍随机获得两个示例
np.random.seed(0) 
x2 = np.random.randint(10,size=(3,4))
#第一行,切满
x3 = x2[0,:]
print(x2,'\n\n',x3)
#第一列,切满
x4 = x2[:,0]
print('\n',x4)
#单取x2[0]
print('\n',x2[0])

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

 [5 0 3 3]

 [5 7 2]

 [5 0 3 3]


如果你希望获得切片的一个克隆,请使用切片的.copy方法

In [17]:
x1 = np.array([5,0,3,3,7,9])
#切分一个片段,但copy
x2 = x1[1:4].copy()
print(x1,x2)
#切下来的部分是原来数组的一个克隆
x2[1] = 10
print(x1,x2)

[5 0 3 3 7 9] [0 3 3]
[5 0 3 3 7 9] [ 0 10  3]


reshape()支持把你已有的数组变成元素同样多但是另一个形状的数组,此外,这个函数返回一个原数组的克隆,当reshape得到的数组和变形后的数组元素数量不一致的时候就会报错

In [18]:
x1 = np.array([5,0,3,3,7,9,1,2,3])
x2 = x1.reshape((3,3))
print(x1)
print(x2)

[5 0 3 3 7 9 1 2 3]
[[5 0 3]
 [3 7 9]
 [1 2 3]]


In [19]:
x1 = np.array([5,0,3,3,7,9,1,2])    #只有八个数,就会报错
x2 = x1.reshape((3,3))
print(x1)
print(x2)

ValueError: cannot reshape array of size 8 into shape (3,3)

对于一个特殊的情况,把一个一维的数组变成二维的但是只有一行的矩阵,我们可以向上面那个例子那样用reshape,也可以用切片中的np.newaxis常量,假装切片

In [20]:
x1 = np.array([5,0,3,3,7])   
x2 = x1[:,np.newaxis]
print(x1)
print(x2)

[5 0 3 3 7]
[[5]
 [0]
 [3]
 [3]
 [7]]


这个例子展示了一个高级用法

In [18]:
x1 = np.array([[1,2],[3,4],[5,6],[7,8]])   
x2 = x1[:,np.newaxis]
x6 = x1[:,:,np.newaxis]
x3 = x1[np.newaxis,:]
x4 = x2 + x3
x5 = np.sum(x4,axis = -1)
print(x1)
print(x1.shape)
print()
print(x2)
print(x2.shape)
print()
print(x3)
print(x3.shape)
print()
print(x4)
print(x4.shape)
print()
print(x5)
print(x5.shape)
print()
print(x6)
print(x6.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)

[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]]
(4, 1, 2)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
(1, 4, 2)

[[[ 2  4]
  [ 4  6]
  [ 6  8]
  [ 8 10]]

 [[ 4  6]
  [ 6  8]
  [ 8 10]
  [10 12]]

 [[ 6  8]
  [ 8 10]
  [10 12]
  [12 14]]

 [[ 8 10]
  [10 12]
  [12 14]
  [14 16]]]
(4, 4, 2)

[[ 6 10 14 18]
 [10 14 18 22]
 [14 18 22 26]
 [18 22 26 30]]
(4, 4)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
(4, 2, 1)


下面是ai对这个操作机理的解释，作为一个ai学生要学会使用ai

    让我用形象的比喻来解释这个NumPy数组维度变换的操作：
    想象你有一串珍珠项链（一维数组x1），现在你想把它改造成一个珍珠展示架（二维数组）。有两种改造方式：
    reshape方式：就像把项链拆开重新排列成单层展示架
    比如：x1.reshape(1,5) → 把5颗珍珠排成1行5列
    np.newaxis方式：就像给项链加个展示支架
    x1[:,np.newaxis] 这个操作可以理解为：
    冒号: 表示"保留所有现有珍珠（元素）"
    np.newaxis 表示"在这里插入一个新的展示维度"
    
    具体到你的例子：
    原始项链： [5,0,3,3,7] （形状(5,)）
    加支架后变成：
    [[5],
    [0],
    [3],
    [3],
    [7]] （形状(5,1)）
    
    关键区别：
    reshape(1,5) → 一行五列的展示架
    [:,np.newaxis] → 五行的单列展示架
    这就像：
    reshape是水平展开（行向量）
    newaxis是垂直展开（列向量）
    
    实际应用中，newaxis常用于：
    需要将一维数组转为列向量进行矩阵运算时
    需要满足某些函数对输入维度的要求时
    进行广播(broadcasting)操作前的维度对齐

拼接或链接两个np数组，可以通过np.concatenate，np.vstack，np.hstack来实现，第一个是简单拼接，譬如123和456拼成123456，他会把数组元素或是数组列表作为第一个参数，以此构造一个新的数组，是参数的拼接，注意到，输入必须是相同维度的数组序列（比如都是1D或都是2D），通过axis参数控制拼接方向，axis参数可以接受任意有效的维度编号，代表其拼接时的方向索引

In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.concatenate([x,y])  #这里的【x，y】就是元素为数组的列表
print(z)

[1 2 3 4 5 6]


In [20]:
x = np.array([1,2,3])
y = np.array([4,5,6])
y2 = np.array([7,8,9])
z = np.concatenate([x,y,y2])  #也可以拼接多个列表
print(z)

[1 2 3 4 5 6 7 8 9]


In [21]:
#二维数组纵向拼接（像叠放书本）
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.concatenate((x,y), axis=0)   #这代表操作发生在行上，后面还会讨论他的
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [22]:
#反之，竖着拼
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.concatenate((x,y), axis=1)
print(z)

[[1 2 5 6]
 [3 4 7 8]]


In [23]:
# 极端例子，创建两个5维数组（形状为 (1,1,1,1,3)）
arr5d_1 = np.ones((1,1,1,1,3))  # 5维全1数组
arr5d_2 = np.zeros((1,1,1,1,3)) # 5维全0数组

# 在第5个维度（axis=4）拼接
result = np.concatenate((arr5d_1, arr5d_2), axis=4)
print(result.shape)  # 输出：(1, 1, 1, 1, 6)


(1, 1, 1, 1, 6)


当你希望沿着水平或是垂直方向拼接数组时，可以用上这俩函数，其是上面一位的简单封装：

‌1. 垂直栈（np.vstack）
‌

‌功能‌：沿第一个维度（axis=0）垂直堆叠数组（行方向拼接）

‌要求‌：所有数组的列数必须相同

‌等效操作‌：np.concatenate(..., axis=0)


反之，‌2. 水平栈（np.hstack）
‌

‌功能‌：沿第二个维度（axis=1）水平堆叠数组（列方向拼接）

‌要求‌：所有数组的行数必须相同

‌等效操作‌：np.concatenate(..., axis=1)


In [24]:
import numpy as np

a = np.array([[1, 2], [3, 4]])  # 形状 (2, 2)
b = np.array([[5, 6]])          # 形状 (1, 2)

result = np.vstack((a, b))      # 垂直拼接
print(result)


[[1 2]
 [3 4]
 [5 6]]


In [25]:
x = np.array([[1, 2], [3, 4]])  # 形状 (2, 2)
y = np.array([[5], [6]])        # 形状 (2, 1)

result = np.hstack((x, y))      # 水平拼接
print(result)


[[1 2 5]
 [3 4 6]]


反之，数组的分裂通过split来实现，当然也有他的h/v版本，这个函数的用法是给他一个记录分裂点位置的索引列表，也提供了axis，允许按维度方向切

In [26]:
original_array = np.array([
    [ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11],
    [12, 13, 14, 15]
])
split_result = np.split(original_array, 2, axis=0)
print(split_result) 
print()
split_result = np.split(original_array, 4, axis=0)  #当第二个参数为整数N时，会将数组沿指定轴均匀切分成N份
print(split_result) 
print()
split_result = np.split(original_array, [1, 3], axis=0)    #当第二个参数为列表时，按指定索引位置切分
print(split_result) 
print()
split_result = np.split(original_array, 2, axis=1)  # 按列分成2部分
print(split_result) 
print()

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]



In [27]:

original_array = np.array([
    [ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11],
    [12, 13, 14, 15]
])


vsplit_result = np.vsplit(original_array, 2)
print(vsplit_result) 
print()

hsplit_result = np.hsplit(original_array, 2)
print(hsplit_result) 
print()


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]



## 计算，numpy的通用函数

python的默认计算实现是相对很慢的，我们将这种语法称为Cpython，因为python会把这些语句动态解释编译，这意味着其不能像是其他的代码那样直接变成高效的机器码，此外，我们在算法课程上也学过，循环是复杂度的来源，我们也知道，代码中能不要写循环就不要写循环，在python中这点特为尤甚，因为python会在每一次循环中都做数据类型的检查和函数的调用，这不慢就有了鬼了

故此，在np中我们为很多操作提供了方便的静态的可编译的程序接口，让我们完成np库所维护的数据类型的计算时可以直接绕开python中复杂度高的部分，而且最重要的是，结合后面的向量化编程思想，我们可以把循环语句也绕过去，numpy会把你构建的向量计算直接推送到python之下的编译层，这就非常的快了

上面我们说的玩意儿通过numpy的通用函数实现，其主要作用是对数组中的值进行更快的重复操作，他的使用是非常灵活的，下面我们就这一点依次举出例子

简单的，在面对两个或是多个np数据类型的加减乘除运算时，直接用python的运算符就可以了

In [30]:
x = np.arange(4)
print(x)
print(x+2)
print(x-2)
print(x*2)
print(x/2)
print(x//2)  #向下取整

[0 1 2 3]
[2 3 4 5]
[-2 -1  0  1]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]


以及指数运算**和取模%

In [32]:
x = np.arange(4)
print(x)
print(x**2)
print(x%2)


[0 1 2 3]
[0 1 4 9]
[0 1 0 1]


换言之，numpy会认为+ - * / 都各自封装了nunpy自己的方法，譬如+ 就等价于 add（），在后面章节我们还会介绍numpy的布尔/位运算

此外，绝对值函数你还可以用abs访问，此时的abs也是np的abs，而非python自己的，这里有一个喜报是，当你试图求一个复数的abs，np会给你返回它的模长，欧拉公式最开心的一集

In [35]:
x = np.array([-1,1,-2,2])
print(abs(x))
y = np.array([-1+1j,-2-2j])    #虚数单位是j
print(abs(y))  #根号2和二倍根号2

[1 1 2 2]
[1.41421356 2.82842712]


numpy还提供了开箱即用的三角函数，显然，角取弧度制，np.degrees()可将结果转为角度制

In [40]:
theta = np.linspace(0,2*np.pi,5)   #得到在0~2pi内均匀分布的5个数
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15
 -2.44929360e-16]


这些值都是在机器精度内计算的，显然会有精确度问题，但是无伤大雅，此外，这里的反三角函数和math不一样，直接就说arctan，而非atan，譬如np.arcsin(x)：计算数组x的反正弦值（弧度制），输入范围需在[-1,1]内，当然，反三角函数最常用的还是arctan，它也提供了输入对边和临边计算顶角的arctan2

In [43]:
x = [-1,0,1]
print(np.arccos(x))
print(np.arctan(x))
print(np.arcsin(x))

[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]
[-1.57079633  0.          1.57079633]


In [47]:
x = 3
y = 5
print(np.arctan2(x,y))

0.5404195002705842


另一个常用的是指数和对数，以a为底的指数函数a powx是np的power方法，特别的，以e为底的是exp，以2为底的是exp2，对数的也提供了简便的以e，2，10为底的对数，基于对数的换底公式，我们实际上可以得到任何我们想要的底，这里的命名方式和国内教材不同，log e x将简写成log 而非ln，而且也没有lg，只有log10

In [48]:
x = [1,2,3]
print(np.exp(x))
print(np.exp2(x))
print(np.power(2,x))

[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[2 4 8]


In [50]:
x = [1,2,3]
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]


补充一嘴，numpy的scipy.special函数提供了很多很奇怪的函数，譬如gamma函数，高斯积分，对的，这些东西被集成到了np中，你百度的时候别忘记它自己已经带了

此外的，所有的通用函数都提供了如下几个功能，譬如指定一个输出位置，可以赋值它的out变量，函数的reduce方法可以持续对一个数组进行该函数操作直到得到一个结果

In [51]:
x = np.arange(5)
y = np.empty(5)
print(x)
print(y)
np.multiply(x,10,out=y)
print(x)
print(y)

[0 1 2 3 4]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15
 -2.44929360e-16]
[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


In [54]:
#小技巧是数组视图
x = np.arange(5)
y = np.zeros(10)
np.power(2,x,out=y[::2])
print(x)
print(y)

[0 1 2 3 4]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [58]:
x = np.arange(1,5)
print(x)
x = np.multiply.reduce(x)    #1到4的累乘
print(x)

[1 2 3 4]
24


In [59]:
x = np.arange(1,5)
print(x)
x = np.multiply.accumulate(x)    #1到4的累乘,并每次记录结果
print(x)

[1 2 3 4]
[ 1  2  6 24]


笛卡尔积

In [60]:
x = np.arange(1,5)
print(x)
x = np.multiply.outer(x,x)    #1到4的累乘,并每次记录结果
print(x)

[1 2 3 4]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


你可能会好奇，哎，我没有sum吗？其实你有的，你不但有sum还有prod，max，min之类的，这一类算作聚合函数

In [62]:
x = np.arange(1,5)
print(x)
print(np.sum(x))
print(np.prod(x))
print(np.max(x))
print(np.min(x))

[1 2 3 4]
10
24
4
1
